spring:
  application:
    name: client
server:
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    registry-fetch-interval-seconds: 30
    healthcheck:
      enabled: true

  instance:
    metadata-map:
      age: 18
      name: 666
      address: zoonm
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 60

ribbon:
    NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RoundRobinRule
