spring:
  application:
    name: Eureka-Client
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    registry-fetch-interval-seconds: 30
    healthcheck:
      enabled: true

  instance:
    metadata-map:
      age: 18
      name: 666
      address: zoonm
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 60


